### ISSUE TITLE
Theme Codes should only contain hex codes

### ISSUE THREAD

**Issue by RichieRunner** [ryan-parag/slack-themes#62]
Currently copying the Theme Codes will also contain the name of the theme:

```
Material Ocean -- 
#0f111a,#121016,#0f111a,#82aaff,#1b1e2d,#dadada,#c3e88d,#c792ea,#0f111a,#dadada
```

This makes it annoying to directly copy/paste the code into Slack, as you have to remove the theme name.

Copy should just contain the hex codes, without the theme name.

**Comment by ryan-parag** [comment]
Copy string should now only contain hex color codes.

Thanks!
